### ISSUE TITLE
Clearly State which LIF(s) are needed for on-premises ONTAP cluster management

### ISSUE THREAD

**Issue by fritntap** [NetAppDocs/bluexp-ontap-onprem#43]
### Page URL

https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html

### Page title

Discover on-premises ONTAP clusters

### Summary

For customers who want to manage on-premises ONTAP clusters with BlueXP, they often ask which ports and LIFs access is required to from BlueXP. This docs page implies that the management LIF is required, but does not clearly state it. I recommend updating the following line to clearly state: _The Connector host must allow outbound connections through port 443 (HTTPS) and the **on-premises** ONTAP cluster must allow inbound HTTP access through port 443 **to the management LIF**_

The General requirements section states: _You need the cluster management IP address and the password for the admin user account._

But, it does not state why these are needed. Therefore, we are assuming a customer will imply that access to the management IP from the BlueXP Connector EC2 instance is needed as part of the statement in the Requirements for Connectivity Discovery section. This small update removes any potential assumptions being made.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Hi @fritntap,

Thank you for submitting this feedback. I went ahead and submitted the change that you suggested. One thing to note is that I did say this: "...to the **cluster** management LIF." 

I thought that might provide additional clarity and not confuse it with a node management LIF.

Thanks again for reaching out.

Regards,
Ben
