### ISSUE TITLE
no instructions for changing a cluster name

### ISSUE THREAD

**Issue by jgknetapp** [NetAppDocs/bluexp-ontap-onprem#49]
### Page URL

https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-view-cluster-info.html

### Page title

View cluster information and contract details

### Summary

there aren't any instructions in any document that describe the procedure for changing a cluster name after it is discovered.   When you perform discovery, you are asked for the IP and login information for a cluster- then when it shows up in your canvas or workspace or whatever you call it this week, it only has the IP address, not the name, and I have spent way too much time trying to figure it out.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@jgknetapp, thanks for reaching out. I'm sorry that this has been frustrating for you.

Are you discovering the on-prem ONTAP cluster with or without a BlueXP Connector?

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
Hi again. I wanted to follow up on my question about whether you were discovering the on-prem ONTAP cluster with or without a BlueXP Connector?

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
If you're still facing this issue, you should reach out to NetApp support. The name of the working environment should be showing up and not the IP address. This could be a potential bug. It's not possible to update the name of the working environment that appears on the BlueXP canvas. 

Regards,
Ben
